name: Docker Telegram Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main
      
    - name: Build the Docker image 
      run: docker build -t telegram:latest --build-arg APP_NAME=telegram .
